---
title: "new_milestone4"
author: "Feven Yohannes"
date: "October 11, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readxl)
library(readr)
library(dplyr)
library(knitr)
library(ggplot2)
library(janitor)
library(gt)
library(tidyverse)
library(httr)
library(rvest)
library(dplyr)
un <- read_html("http://data.un.org/en/iso/et.html", skip=4, col_names=TRUE)
tbls <- html_nodes(un, "table")
un_tbl <- un %>%
        html_nodes("table") %>%
        .[3:4] %>%
        html_table(fill = TRUE, header=TRUE)

test <- un_tbl %>% map_df(bind_rows)

un_tbl
world_bank <- read_csv("/Users/feven/Documents/Gov1005/Final Project/Milestone_4/API_ETH_DS2_en_csv_v2_205341.csv") 

pop<- read_xlsx("/Users/feven/Documents/Gov1005/Final Project/new_milestone4/eth_populatedplaces_tabulardata.xlsx")
```

```{r}
pop %>%
  select(admin1Name_en, popPlaceClassNumber, featureName_en) %>%
  filter(admin1Name_en=="Tigray") %>%
  arrange(desc(popPlaceClassNumber)) %>%
  ggplot(aes(x=popPlaceClassNumber),fill=popPlaceClassNumber) +geom_histogram(bins=8) +
   labs(title ="Population of Different Cities in the Tigray Region of Ethiopia",
        subtitle="Majority of Cities are Heavily Populated",
         x = "Population Indicator",
         y="Number of Cities")
  
```

